name: live publish🚀

env:
  AZURE_WEBAPP_NAME: invyoc
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  DOTNET_VERSION: '8.x'
  
on:
  workflow_dispatch:
  push:
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Restore
        run: dotnet restore ./invyoc.sln

      - name: Build
        run: dotnet build ./invyoc.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./invyoc.sln -c Release --no-build

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}